---
# tasks file for jenkins_docker
- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Set timezone to Europe/Moscow
  community.general.timezone:
    name: Europe/Moscow

- name: install Chrony
  ansible.builtin.apt:
    name: chrony 
    state: latest
    update_cache: true
  notify: Enable Chrony  

- name: Allow connections on multiple ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "8080"
    jump: ACCEPT

- name: Install JRE and JDK
  apt: 
    name: "{{ item }}"
    update_cache: yes
    install_recommends: no
  loop:
    - "openjdk-11-jre"
    - "openjdk-11-jdk"

- name: One way to avoid apt_key once it is removed from your distro
  block:
    - name: somerepo |no apt key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: somerepo | apt source
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    update_cache: true
  notify: Enable Jenkins  